### ISSUE TITLE
Not compatible with integration_test package

### ISSUE THREAD

**Issue by shinayser** [felixblaschke/shelf_hotreload#2]
Sup @felixblaschke whats up bro?

We found a problem on our app using the integration test with `shelf_hotreload` because of incompatible libraries. Actually the problem was not `shelf_hotreload` itself, but the `dart-hotreloader` package.

I've alteady got in touch with its maintainer and he already fixed it [here](https://github.com/vegardit/dart-hotreloader/issues/4). He already uploaded a version 3.0.2 on pub.dev but we still need you to update `shelf_hotreload` on pub.dev using this 3.0.2 version of hotreloader to fix this once and for all.

Can we count on you?

Best regards!!

**Comment by felixblaschke** [comment]
Hi, thank you for the explanation. I upgraded the dependencies and release 1.0.1 of shelf_hotreload.

**Comment by shinayser** [comment]
Hey Felix thanks for your efforts. Everything is working fine now :)
